config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "general_settings#index"
  post '/api/sync_ticket', to: "api#sync_ticket"
  post '/api/sync_setting', to: "api#sync_setting" 
  get '/access_settings', to: "api#access_settings"
  post '/generate/api_key', to: "api#generate_api_key"

  resources :general_settings do
    get "download_assets", on: :collection
  end
  resources :user_settings
  resources :csv
  resources :fs_assets do
    post "upload", on: :collection
    get "sync", on: :collection
  end
  resources :service_requests do
    get "download", on: :collection
    get "file_not_found", on: :collection
  end
end

app/controllers/user_settings_controller.rb
class UserSettingsController < ApplicationController
  before_action :authenticate_user!
  def index
    # @users = User.where(id: current_user.id).page(params[:page] || 1).per(20)  
    @users = User.where.not(id: current_user.id).page(params[:page] || 1).per(20)  
  end

  def new
    @user = User.new()  
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to "/user_settings", notice: "User added"
    else
      render 'new'
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to "/user_settings", notice: "User details updated"
    else
      render 'edit'
    end
  end

  private
    def user_params
      params.require(:user).permit(:id, :email, :full_name, :password, :password_confirmation)
    end
end

app/helpers/user_settings_helper.rb
module UserSettingsHelper
end

app/views/user_settings/edit.html.erb
<div class="row mt-3 mb-3 ml-3 mr-3">
  <div class="col">
    <b>Edit User Details</b>
  </div>
  <div class="col text-right">
    <a href="/user_settings" class="btn btn-secondary btn-sm"><i class="fas fa-times"></i> Cancel</a>
  </div>
</div>
<div class="row pl-3 pr-3 ml-3 mr-3">
  <div class="col border-gray pt-3 rounded bg-gray form-group">
    <div class="row pb-1">
      <div class="col">
        <%= form_for @user, method: "PUT", url: user_setting_path do |f| %>
          <% if @user.errors.present? %>
            <script>toastr.warning('<%= @general_settings.try(:errors).try(:full_messages).try(:first) %>')</script>
          <% end %>
          <div class="row">
            <div class="col">
              <div class="form-group">
                <%= f.label "Full Name", class: "font-weight-light" %>
                <%= f.text_field :full_name, class: "form-control form-control-sm", autofocus: true %>
              </div>
            </div>
            <div class="col">
              <div class="form-group">
                <%= f.label "Email", class: "font-weight-light" %>
                <%= f.email_field :email, class: "form-control form-control-sm" %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col">
              <div class="form-group">
                <%= f.label "Password", class: "font-weight-light" %>
                <%= f.password_field :password, class: "form-control form-control-sm" %>
              </div>
            </div>
            <div class="col">
              <div class="form-group">
                <%= f.label "Password Confirmation", class: "font-weight-light" %>
                <%= f.password_field :password_confirmation, class: "form-control form-control-sm" %>
              </div>
            </div>
          </div>
          <div class="form-group text-right">
            <%= f.submit "Update User Details", class: "btn btn-primary btn-sm" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/user_settings/index.html.erb
<div class="row mt-3 mb-3 ml-3 mr-3">
  <div class="col">
    <b>Users List</b>
  </div>
  <div class="col text-right">
    <a href="/user_settings/new" class="btn btn-primary btn-sm"><i class="fas fa-user-plus"></i> Add User</a>
  </div>
</div>
  
<div class="row mt-3 mb-3 ml-3 mr-3">
  <div class="col">
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col" width="50%">Full Name</th>
          <th scope="col">Email</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <th scope="row"><%= user.id %></th>
            <td><%= user.full_name %></td>
            <td><%= user.email %></td>
            <td><a href="/user_settings/<%= user.id %>/edit"><i class="fas fa-user-edit"></i> Edit</a> </td>
          </tr>  
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<div class="row">
  <div class="col text-right pl-5 pr-5">
    <%= paginate @users %>
  </div>
</div>

app/views/user_settings/new.html.erb
<div class="row mt-3 mb-3 ml-3 mr-3">
  <div class="col">
    <b>New User</b>
  </div>
  <div class="col text-right">
    <a href="/user_settings" class="btn btn-secondary btn-sm"><i class="fas fa-times"></i> Cancel</a>
  </div>
</div>
<div class="row pl-3 pr-3 ml-3 mr-3">
  <div class="col border-gray pt-3 rounded bg-gray form-group">
    <div class="row pb-1">
      <div class="col">
        <%= form_for @user, method: "POST", url: user_settings_path do |f| %>
          <% if @user.errors.present? %>
            <script>toastr.warning('<%= @general_settings.try(:errors).try(:full_messages).try(:first) %>')</script>
          <% end %>
          <div class="row">
            <div class="col">
              <div class="form-group">
                <%= f.label "Full Name", class: "font-weight-light" %>
                <%= f.text_field :full_name, class: "form-control form-control-sm", autofocus: true %>
              </div>
            </div>
            <div class="col">
              <div class="form-group">
                <%= f.label "Email", class: "font-weight-light" %>
                <%= f.email_field :email, class: "form-control form-control-sm" %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col">
              <div class="form-group">
                <%= f.label "Password", class: "font-weight-light" %>
                <%= f.password_field :password, class: "form-control form-control-sm" %>
              </div>
            </div>
            <div class="col">
              <div class="form-group">
                <%= f.label "Password Confirmation", class: "font-weight-light" %>
                <%= f.password_field :password_confirmation, class: "form-control form-control-sm" %>
              </div>
            </div>
          </div>
          <div class="form-group text-right">
            <%= f.submit "Save User", class: "btn btn-primary btn-sm" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>